spring.application.name=spring-demo
spring.datasource.url=jdbc:postgresql://localhost:5432/yzl3514
spring.datasource.username=devlab
spring.datasource.password=S3cR3t

logging.level.org.springframework.data.jdbc=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
